"""Phase-2 tie-outs: employee summary, group breakdowns + weighted-avg-DPD,
proactive risk flags, and the full data-quality audit list.

Every value is asserted against the independent oracle in
``expected_small.json`` (regenerated by tests/fixtures/build_fixtures.py, which
shares no code with src/tools). Money is compared in exact integer paise;
weighted-average days overdue is compared as the rounded float both sides emit.
"""

from datetime import date

from graph.runner import run_analysis
from tools.ingest import normalize, read_workbook
from tools.metrics import compute_metrics

AS_OF = date(2026, 1, 15)


def _paise(rupees: float) -> int:
    return round(rupees * 100)


def _run(small_xlsx_bytes, small_mapping):
    return run_analysis(
        file_bytes=small_xlsx_bytes, sheet_name=None, mapping=small_mapping, as_of=AS_OF
    )


# --------------------------------------------------------------------------- #
# 1. Per-employee summary
# --------------------------------------------------------------------------- #
def test_employee_summary_matches_oracle(small_xlsx_bytes, small_mapping, expected_small):
    m = _run(small_xlsx_bytes, small_mapping)
    got = [
        (
            e.employee,
            _paise(e.total_outstanding),
            _paise(e.total_overdue),
            e.worst_bucket,
            e.invoice_count,
        )
        for e in m.employees
    ]
    want = [
        (
            e["employee"],
            e["total_outstanding_paise"],
            e["total_overdue_paise"],
            e["worst_bucket"],
            e["invoice_count"],
        )
        for e in expected_small["employees"]
    ]
    assert got == want, (got, want)

    # Ranked descending by outstanding, with the seeded blank-employee row present.
    assert [e.employee for e in m.employees] == ["Ravi", "Priya", "(blank)"]
    assert any(e.employee == "(blank)" for e in m.employees)

    # pct_overdue matches to full float precision.
    for got_e, want_e in zip(m.employees, expected_small["employees"]):
        assert abs(got_e.pct_overdue - want_e["pct_overdue"]) < 1e-12


def test_employee_partition_invariant(small_xlsx_bytes, small_mapping):
    """Sum of per-employee outstanding == overall total_outstanding (exact paise)."""
    m = _run(small_xlsx_bytes, small_mapping)
    assert sum(_paise(e.total_outstanding) for e in m.employees) == _paise(m.total_outstanding)


# --------------------------------------------------------------------------- #
# 2. Group aging breakdowns + weighted-avg-DPD
# --------------------------------------------------------------------------- #
def _breakdown_tuples(rows):
    """(key, bucket_paise dict, wavg, outstanding_paise) from models."""
    out = []
    for b in rows:
        bt = b.bucket_totals
        out.append(
            (
                b.key,
                {
                    "current": _paise(bt.current),
                    "0-30": _paise(bt.b_0_30),
                    "31-60": _paise(bt.b_31_60),
                    "61-90": _paise(bt.b_61_90),
                    "90+": _paise(bt.b_90_plus),
                },
                b.weighted_avg_days_overdue,
                _paise(b.total_outstanding),
            )
        )
    return out


def _oracle_breakdown_tuples(rows):
    out = []
    for b in rows:
        out.append(
            (
                b["key"],
                {k: v for k, v in b["bucket_totals_paise"].items()},
                b["weighted_avg_days_overdue"],
                b["total_outstanding_paise"],
            )
        )
    return out


def test_customer_breakdown_matches_oracle(small_xlsx_bytes, small_mapping, expected_small):
    m = _run(small_xlsx_bytes, small_mapping)
    assert _breakdown_tuples(m.customer_breakdown) == _oracle_breakdown_tuples(
        expected_small["customer_breakdown"]
    )

    # The all-current customer returns null weighted-avg (never 0, never /0).
    zenith = next(b for b in m.customer_breakdown if b.key == "Zenith Ltd")
    assert zenith.weighted_avg_days_overdue is None

    # A deep-90+ and a mixed-bucket customer carry real weighted averages.
    beacon = next(b for b in m.customer_breakdown if b.key == "Beacon & Co")
    assert beacon.weighted_avg_days_overdue == 200.33
    acme = next(b for b in m.customer_breakdown if b.key == "Acme Corp")
    assert acme.weighted_avg_days_overdue == 55.22


def test_employee_breakdown_matches_oracle(small_xlsx_bytes, small_mapping, expected_small):
    m = _run(small_xlsx_bytes, small_mapping)
    assert _breakdown_tuples(m.employee_breakdown) == _oracle_breakdown_tuples(
        expected_small["employee_breakdown"]
    )


def test_breakdown_partition_invariants(small_xlsx_bytes, small_mapping):
    """(a) group outstanding sums to overall; (b) per-bucket group sums == overall
    bucket totals — for BOTH the customer and employee partitions. The five bucket
    amounts intentionally do NOT sum to a group's outstanding (Acme has an
    unclassified, no-due-date row of 500,000)."""
    m = _run(small_xlsx_bytes, small_mapping)
    overall = {
        "current": _paise(m.bucket_totals.current),
        "0-30": _paise(m.bucket_totals.b_0_30),
        "31-60": _paise(m.bucket_totals.b_31_60),
        "61-90": _paise(m.bucket_totals.b_61_90),
        "90+": _paise(m.bucket_totals.b_90_plus),
    }
    overall_out = _paise(m.total_outstanding)

    for partition in (m.customer_breakdown, m.employee_breakdown):
        # (a) exact outstanding partition
        assert sum(_paise(b.total_outstanding) for b in partition) == overall_out
        # (b) exact per-bucket partition
        for bucket, field in (
            ("current", "current"),
            ("0-30", "b_0_30"),
            ("31-60", "b_31_60"),
            ("61-90", "b_61_90"),
            ("90+", "b_90_plus"),
        ):
            got = sum(_paise(getattr(b.bucket_totals, field)) for b in partition)
            assert got == overall[bucket], (bucket, got, overall[bucket])

    # The 5 buckets do NOT sum to Acme's outstanding (proves unclassified handling).
    acme = next(b for b in m.customer_breakdown if b.key == "Acme Corp")
    five = sum(
        _paise(getattr(acme.bucket_totals, f))
        for f in ("current", "b_0_30", "b_31_60", "b_61_90", "b_90_plus")
    )
    assert five == _paise(acme.total_outstanding) - 50000000  # 500,000 unclassified


# --------------------------------------------------------------------------- #
# 3. Proactive risk flags
# --------------------------------------------------------------------------- #
def test_risk_flags_rank_beacon_first(small_xlsx_bytes, small_mapping, expected_small):
    m = _run(small_xlsx_bytes, small_mapping)
    got = [(f.customer, f.reason, _paise(f.amount), f.bucket) for f in m.risk_flags]
    want = [
        (f["customer"], f["reason"], _paise(f["amount"]), f["bucket"])
        for f in expected_small["risk_flags"]
    ]
    assert got == want
    assert m.risk_flags[0].customer == "Beacon & Co"
    assert m.risk_flags[0].reason == "largest 90+ overdue"
    assert m.risk_flags[0].bucket == "90+"
    # Only Beacon & Acme have any 90+ balance.
    assert [f.customer for f in m.risk_flags] == ["Beacon & Co", "Acme Corp"]


# --------------------------------------------------------------------------- #
# 4. Full data-quality audit list
# --------------------------------------------------------------------------- #
def test_data_quality_rows_list_seeded_flags(small_xlsx_bytes, small_mapping, expected_small):
    m = _run(small_xlsx_bytes, small_mapping)
    got = {(r.row_index, r.field, r.reason) for r in m.data_quality.rows}
    want = {(f["row_index"], f["field"], f["reason"]) for f in expected_small["flags"]}
    assert got == want
    # The seeded bad rows are indices 14/15/16/17.
    assert {r.row_index for r in m.data_quality.rows} == {14, 15, 16, 17}
    # Counts unchanged by populating the audit list.
    assert m.data_quality.flagged_row_count == 4
    assert len(m.data_quality.rows) == len(expected_small["flags"])


# --------------------------------------------------------------------------- #
# 5. Flags are advisory — they never change the computed totals
# --------------------------------------------------------------------------- #
def test_flags_do_not_change_total_outstanding(small_xlsx_bytes, small_mapping):
    """Total outstanding is identical whether or not the flags/audit are built."""
    df, _ = read_workbook(small_xlsx_bytes, None)
    without_flags = compute_metrics(normalize(df, small_mapping, AS_OF), AS_OF)
    with_flags = _run(small_xlsx_bytes, small_mapping)
    assert _paise(without_flags.total_outstanding) == _paise(with_flags.total_outstanding)
    assert _paise(without_flags.total_overdue) == _paise(with_flags.total_overdue)
